### ISSUE TITLE
PA11 

### ISSUE THREAD

**Issue by lowtolerance** [bigtreetech/SKRat#1]
Pin PB11 is used twice for E1M’s UART and STEP pins. Which one is correct??

**Comment by NickyDrinks** [comment]
This has been fixed, it's PB10 for E1M STP and PB11 is only used once on NSS. I had taken the correct settings from the RatOS config to get around the wonky labelling on BTT's but I can confirm that it works. I'm not sure why they didn't update and close this issue, but just in case you won't see it without a reply here.
